# Generated by Django 2.0.1 on 2018-08-03 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oragnization', '0003_auto_20180802_1233'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oragnization.CourseOrg', verbose_name='所属机构'),
        ),
    ]
