# Generated by Django 2.0.1 on 2018-08-13 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oragnization', '0004_teacher_image'),
        ('course', '0007_video_learn_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oragnization.Teacher', verbose_name='课程讲师'),
        ),
    ]
