# Generated by Django 2.0.1 on 2018-08-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180820_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('change', '更改邮箱')], max_length=20, verbose_name='验证码类型'),
        ),
    ]
