# Generated by Django 2.0.1 on 2018-08-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oragnization', '0005_teacher_work_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=0, max_length=3, verbose_name='年龄'),
        ),
    ]
