# Generated by Django 2.0.1 on 2018-08-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oragnization', '0007_auto_20180815_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='国内名牌', max_length=10, verbose_name='机构标签'),
        ),
    ]
